const carros = [
  {
    id: 1,
    nome: "Relâmpago McQueen",
    modelo: "Carro de Corrida",
    ano: 2006,
    cor: "Vermelho",
    qtdeVitorias: 7,
  },
  {
    id: 2,
    nome: "Mate",
    modelo: "Caminhão Reboque",
    ano: 1951,
    cor: "Marrom",
    qtdeVitorias: 0,
  },
  {
    id: 3,
    nome: "Sally Carrera",
    modelo: "Porsche 911 Carrera",
    ano: 2002,
    cor: "Azul",
    qtdeVitorias: 0,
  },
  {
    id: 4,
    nome: "Doc Hudson",
    modelo: "Hudson Hornet",
    ano: 1951,
    cor: "Azul Escuro",
    qtdeVitorias: 3,
  },
  {
    id: 5,
    nome: "Ramone",
    modelo: "Impala Lowrider",
    ano: 1959,
    cor: "Roxo",
    qtdeVitorias: 0,
  },
  {
    id: 6,
    nome: "Sheriff",
    modelo: "Mercury Police Cruiser",
    ano: 1949,
    cor: "Preto",
    qtdeVitorias: 0,
  },
  {
    id: 7,
    nome: "Filmore",
    modelo: "Volkswagen Bus",
    ano: 1960,
    cor: "Verde Claro",
    qtdeVitorias: 0,
  },
  {
    id: 8,
    nome: "Sargento",
    modelo: "Jeep Willys",
    ano: 1942,
    cor: "Verde Escuro",
    qtdeVitorias: 0,
  },
  {
    id: 9,
    nome: "Guido",
    modelo: "Empilhadeira",
    ano: 1968,
    cor: "Amarelo",
    qtdeVitorias: 0,
  },
  {
    id: 10,
    nome: "Luigi",
    modelo: "Fiat 500",
    ano: 1957,
    cor: "Amarelo",
    qtdeVitorias: 0,
  },
];

export default { carros };
